#!/bin/bash
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT

# Setup task 2/4 (job_type:srun, requires_gpus:true).
#
# Write srt-slurm/srtslurm.yaml from the SLURM env vars the framework
# injects (via augment_env_for_job_type).
#
# Why job_type:srun rather than local:
#   `local` setup tasks get NO SLURM env vars from the framework, and
#   $LLMB_INSTALL/cluster_config.yaml is not written until AFTER all
#   setup tasks succeed — so a local task has no way to learn the
#   cluster's account/partition. The framework runs `srun` tasks INLINE
#   on the install host (subprocess.run with augmented env, no actual
#   srun dispatch). It is the lightest-weight job_type that exposes
#   SLURM_ACCOUNT + SLURM_PARTITION.
#
# Why requires_gpus:true:
#   We want SLURM_PARTITION = gpu_partition (where the benchmark
#   sbatches via `srtctl apply -f`), not cpu_partition.

set -eu -o pipefail

export LLMB_WORKLOAD=${LLMB_WORKLOAD:?LLMB_WORKLOAD not set (framework should provide).}
export SLURM_ACCOUNT=${SLURM_ACCOUNT:?SLURM_ACCOUNT not set.}
export SLURM_PARTITION=${SLURM_PARTITION:?SLURM_PARTITION not set.}

SRT_SLURM_DIR="$LLMB_WORKLOAD/srt-slurm"
OUT="$SRT_SLURM_DIR/srtslurm.yaml"

[[ -d $SRT_SLURM_DIR ]] || {
    echo "[generate_srtslurm_yaml] ERROR: srt-slurm not cloned at $SRT_SLURM_DIR. install_srtslurm must run first." >&2
    exit 1
}

# Don't clobber a hand-edited srtslurm.yaml. Users may have added
# model_paths / containers blocks specific to their cluster, and
# srt-slurm's `make setup` itself skips creation when the file exists.
if [[ -f $OUT ]]; then
    echo "[generate_srtslurm_yaml] $OUT already exists — leaving it alone."
    exit 0
fi

# $SLURM_GPUS_PER_NODE is empty on clusters that don't configure GRES.
# we target Grace SKUs only for now (gb200/gb300), all of which have
# 4 GPUs/node — fall back to 4.
GPUS_PER_NODE="${SLURM_GPUS_PER_NODE:-4}"

cat > "$OUT" << EOF
# Generated by the generate_srtslurm_yaml setup task during llmb-install.
# Safe to edit by hand after install — the generator does not clobber an
# existing srtslurm.yaml on re-run.

default_account: "$SLURM_ACCOUNT"
default_partition: "$SLURM_PARTITION"
default_time_limit: "5:00:00"

gpus_per_node: $GPUS_PER_NODE
network_interface: ""

# SBATCH directive compatibility. Each flag toggles whether the corresponding
# #SBATCH directive is emitted when the benchmark is sbatched:
#   use_gpus_per_node_directive    → #SBATCH --gpus-per-node=N
#   use_segment_sbatch_directive   → #SBATCH --segment=...
#   use_exclusive_sbatch_directive → #SBATCH --exclusive
# The values below are tuned for typical NVIDIA Grace clusters (gb200/gb300).
# If your cluster's sbatch rejects them (e.g. "Invalid generic resource
# (gres) specification"), flip the offending flag.
use_gpus_per_node_directive: false
use_segment_sbatch_directive: false
use_exclusive_sbatch_directive: true

srtctl_root: "$SRT_SLURM_DIR"
EOF
echo "[generate_srtslurm_yaml] wrote $OUT"
echo "[generate_srtslurm_yaml]   default_account=$SLURM_ACCOUNT"
echo "[generate_srtslurm_yaml]   default_partition=$SLURM_PARTITION"
echo "[generate_srtslurm_yaml]   gpus_per_node=$GPUS_PER_NODE"
